export const easyMode = [
    {
        prompt: '1. Who possesses the ring of power at the start of the trilogy?',
        optionA: 'Gandalf',
        optionB: 'Bilbo',
        optionC: 'Sauron',
        optionD: 'Frodo',
        answer: "B",
        imageUrl: "https://i.etsystatic.com/19698451/r/il/e1649e/3938380927/il_fullxfull.3938380927_5f01.jpg"
    },
    {
        prompt: '2. Who do the hobbits encounter at the Prancing Pony?',
        optionA: 'Gandalf',
        optionB: 'Legolas',
        optionC: 'Aragorn',
        optionD: 'Boromir',
        answer: "C",
    },
    {
        prompt: '3. How many members make up the fellowship of the ring?',
        optionA: 'Nine',
        optionB: 'Five',
        optionC: 'Seven',
        optionD: 'Eight',
        answer: "D",
    },
    {
        prompt: '4. What race is Frodo Baggins?',
        optionA: 'Dwarf',
        optionB: 'Elf',
        optionC: 'Hobbit',
        optionD: 'Orc',
        answer: "C",
    },
    {
        prompt: '5. The Lord of the Rings begins with a party celebrating what?',
        optionA: 'Bilbo\'s 111th birthday',
        optionB: 'The New Year',
        optionC: 'Merry\'s birthday',
        optionD: 'Gandalf\'s arrival to the Shire',
        answer: "A",
    },
    {
        prompt: '6. What\'s Legolas main weapon?',
        optionA: 'Sword',
        optionB: 'Mace',
        optionC: 'Bow',
        optionD: 'Frying Pan',
        answer: "C",
    },
    {
        prompt: '7. Who has been following Sam and Frodo?',
        optionA: 'Gollum',
        optionB: 'Smeagol',
        optionC: 'A and B',
        optionD: 'Azog',
        answer: "C",
    },
    {
        prompt: '8. What King refused to throw the One Ring into Mount Doom?',
        optionA: 'Isildur',
        optionB: 'Elendil',
        optionC: 'Elrond',
        optionD: 'Tranduil',
        answer: "A",
    },
    {
        prompt: '9. What is Bilbo and Frodo Baggins home called?',
        optionA: 'Rohan',
        optionB: 'Rivendell',
        optionC: 'Lothlórien',
        optionD: 'Bag End',
        answer: "D",
    },
    {
        prompt: '10. What is the name of the dwarf in the fellowship?',
        optionA: 'Merry',
        optionB: 'Sam',
        optionC: 'Gimli',
        optionD: 'Boromir',
        answer: "C",
    },
]