export const easyMode = [
    {
        prompt: '1. Who possesses the ring of power at the start of the trilogy?',
        optionA: 'Gandalf',
        optionB: 'Bilbo',
        optionC: 'Sauron',
        optionD: 'Frodo',
        answer: "B",
    },
    {
        prompt: '2. Who do the hobbits encounter at the Prancing Pony?',
        optionA: 'Gandalf',
        optionB: 'Legolas',
        optionC: 'Aragorn',
        optionD: 'Boromir',
        answer: "C",
    },
    {
        prompt: '3. How many members make up the fellowship of the ring?',
        optionA: 'Nine',
        optionB: 'Five',
        optionC: 'Seven',
        optionD: 'Eight',
        answer: "D",
    },
    {
        prompt: '4. What race is Frodo Baggins?',
        optionA: 'Dwarf',
        optionB: 'Elf',
        optionC: 'Hobbit',
        optionD: 'Orc',
        answer: "C",
    },
    {
        prompt: '5. The Lord of the Rings begins with a party celebrating what?',
        optionA: 'Bilbo\'s 111th birthday',
        optionB: 'The New Year',
        optionC: 'Merry\'s birthday',
        optionD: 'Gandalf\'s arrival to the Shire',
        answer: "A",
    },
    {
        prompt: '6. What\'s Legolas main weapon?',
        optionA: 'Sword',
        optionB: 'Mace',
        optionC: 'Bow',
        optionD: 'Frying Pan',
        answer: "C",
    },
    {
        prompt: '7. Who has been following Sam and Frodo?',
        optionA: 'Gollum',
        optionB: 'Smeagol',
        optionC: 'A and B',
        optionD: 'Azog',
        answer: "C",
    },
    {
        prompt: '8. What King refused to throw the One Ring into Mount Doom?',
        optionA: 'Isildur',
        optionB: 'Elendil',
        optionC: 'Elrond',
        optionD: 'Tranduil',
        answer: "A",
    },
    {
        prompt: '9. What is Bilbo and Frodo Baggins home called?',
        optionA: 'Rohan',
        optionB: 'Rivendell',
        optionC: 'Lothlórien',
        optionD: 'Bag End',
        answer: "D",
    },
    {
        prompt: '10. What is the name of the dwarf in the fellowship?',
        optionA: 'Merry',
        optionB: 'Sam',
        optionC: 'Gimli',
        optionD: 'Boromir',
        answer: "C",
    },
]

export const mediumMode = [
    {
        prompt: '1. When the pass of Caradhras is blocked, where does Frodo say the fellowship should go?',
        optionA: 'Rivendell',
        optionB: 'Lothlorien',
        optionC: 'Moria',
        optionD: 'Minas Tirith',
        answer: "C",
    },
    {
        prompt: '2. Who is the first member of the fellowship to be separated from the group?',
        optionA: 'Gandalf',
        optionB: 'Legolas',
        optionC: 'Boromir',
        optionD: 'Aragorn',
        answer: "A",
    },
    {
        prompt: '3. What happens at the end of the first movie?',
        optionA: 'Merry and Pippin are carried off by orcs and Uruk-hai',
        optionB: 'Boromir is killed',
        optionC: 'Frodo and Sam leave the others behind',
        optionD: 'All of the above',
        answer: "D",
    },
    {
        prompt: '4. Who is the king of Rohan?',
        optionA: 'Wormtongue',
        optionB: 'Éowyn',
        optionC: 'Théoden',
        optionD: 'Éomer',
        answer: "C",
    },
    {
        prompt: '5. Where is Saruman’s tower, Orthanc, located?',
        optionA: 'Minas Tirith',
        optionB: 'Rivendell',
        optionC: 'Helm’s Deep',
        optionD: 'Isengard',
        answer: "D",
    },
    {
        prompt: '6. What animal does Gollum give to Frodo?',
        optionA: 'A ferret',
        optionB: 'A rabbit',
        optionC: 'A mouse',
        optionD: 'A fish',
        answer: "B",
    },
    {
        prompt: '7. Where does Théoden decide to send his people?',
        optionA: 'Minas Tirith',
        optionB: 'Rivendell',
        optionC: 'Helm’s Deep',
        optionD: 'Isengard',
        answer: "C",
    },
    {
        prompt: '8. Whom does Aragorn love?',
        optionA: 'Éowyn',
        optionB: 'Galadriel',
        optionC: 'Arwen',
        optionD: 'None of the above',
        answer: "C",
    },
    {
        prompt: '9. Who shows up to help defend Helm’s Deep at the last moment?',
        optionA: 'The riders of Rohan, led by Éomer',
        optionB: 'An elf army',
        optionC: 'The Ents',
        optionD: 'All of the above',
        answer: "D",
    },
    {
        prompt: '10. What forest creatures do Pippin and Merry come across?',
        optionA: 'Orcs',
        optionB: 'Ents',
        optionC: 'Rabbits',
        optionD: 'Uruk-hai',
        answer: "B",
    },
]

export const hardMode = [
    {
        prompt: '1. At Weathertop, the hobbits are attacked by Ringwraiths. How many are there?',
        optionA: '3',
        optionB: '6',
        optionC: '5',
        optionD: '9',
        answer: "D",
    },
    {
        prompt: '2. Who stole the ring from the original owner?',
        optionA: 'Isildur',
        optionB: 'Elrond',
        optionC: 'Elendil',
        optionD: 'Saruman',
        answer: "A",
    },
    {
        prompt: '3. What is the title of J.R.R Tolkien\'s book about Bilbo?',
        optionA: 'There and back again: A Hobbit’s Tale',
        optionB: 'There and back again: A Hobbit’s Story',
        optionC: 'There and back again: A Hobbit’s Journey',
        optionD: 'There and back again: A Hobbit’s Travels',
        answer: "A",
    },
    {
        prompt: '4. Who is the first elf to appear in the movie?',
        optionA: 'Legolas',
        optionB: 'Elrond',
        optionC: 'Haldir',
        optionD: 'Arwen',
        answer: "D",
    },
    {
        prompt: '5. What colour is Bilbo Baggins’ door?',
        optionA: 'White',
        optionB: 'Green',
        optionC: 'Red',
        optionD: 'Yellow',
        answer: "D",
    },
    {
        prompt: '6. What book did Tolkien want to publish simultaneously with The Lord of the Rings?',
        optionA: 'The Hobbit',
        optionB: 'The Silmarillion',
        optionC: 'The Adventures of Tom Bombadil',
        optionD: 'The Adventures of Bilbo Baggins',
        answer: "B",
    },
    {
        prompt: '6. What is the name of the giant spider who tried to eat Frodo?',
        optionA: 'Balrog',
        optionB: 'Morgoth',
        optionC: 'Shelob',
        optionD: 'Ungoliant',
        answer: "C",
    },
    {
        prompt: '7. When was Lord of the Rings first published?',
        optionA: '1954',
        optionB: '1958',
        optionC: '1962',
        optionD: '1966',
        answer: "A",
    },
    {
        prompt: '8. The shards of the sword Narsil were taken to Rivendell and reforged into what new sword?',
        optionA: 'Orcrist',
        optionB: 'Glamdring',
        optionC: 'Anduril',
        optionD: 'Sting',
        answer: "C",
    },
    {
        prompt: '9. In "Lord of the Rings," Arwen chooses to give up her immortality to be with her love, Aragorn, who is a mortal man. Why is she able to do this?',
        optionA: 'All elves can choose to be mortal.',
        optionB: 'She has human ancestors.',
        optionC: 'She gives away her Evanstar necklace.',
        optionD: 'She is a valar.',
        answer: "B",
    },
    {
        prompt: '10. What does Elrond offer to Aragorn?',
        optionA: 'The evenstar',
        optionB: 'A ring',
        optionC: 'A sword',
        optionD: 'Immortal life',
        answer: "C",
    },
]